import {
  AIAgent,
  AgentRole,
  AgentWorkProtocolStep,
  AppMetadata,
  AttentionItem,
  CompanyDecision,
  CompanyInitiative,
  CustomerDeal,
  FinanceMetric,
  OSNotification,
  OrchestrationRun,
  ProductFeature,
  ResearchTopic,
  WindowState,
} from '@/types/os';

export const INITIAL_WINDOWS: WindowState[] = [
  {
    id: 'workforce',
    title: 'SamJuniors OS — Company Headquarters',
    isOpen: true,
    isMinimized: false,
    isMaximized: false,
    zIndex: 10,
    position: { x: 70, y: 55 },
    size: { width: 1040, height: 680 },
  },
  {
    id: 'company',
    title: 'Company Governance & OKRs',
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    zIndex: 9,
    position: { x: 120, y: 80 },
    size: { width: 880, height: 580 },
  },
  {
    id: 'customers',
    title: 'Autonomous CRM & Accounts',
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    zIndex: 8,
    position: { x: 140, y: 90 },
    size: { width: 900, height: 580 },
  },
  {
    id: 'research',
    title: 'Market Intel & Research Radar',
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    zIndex: 7,
    position: { x: 160, y: 100 },
    size: { width: 900, height: 580 },
  },
  {
    id: 'products',
    title: 'Product Roadmap & PRDs',
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    zIndex: 6,
    position: { x: 180, y: 110 },
    size: { width: 900, height: 580 },
  },
  {
    id: 'finance',
    title: 'Finance & Token Economics',
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    zIndex: 5,
    position: { x: 200, y: 120 },
    size: { width: 880, height: 580 },
  },
  {
    id: 'settings',
    title: 'OS Settings & Autonomy',
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    zIndex: 4,
    position: { x: 220, y: 130 },
    size: { width: 780, height: 540 },
  },
  {
    id: 'terminal',
    title: 'SamJuniors CLI Terminal',
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    zIndex: 3,
    position: { x: 240, y: 140 },
    size: { width: 720, height: 480 },
  },
  {
    id: 'notes',
    title: 'Founder Scratchpad',
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    zIndex: 2,
    position: { x: 260, y: 150 },
    size: { width: 680, height: 460 },
  },
];

export const APPS_CONFIG: AppMetadata[] = [
  {
    id: 'workforce',
    name: 'Company HQ',
    category: 'Executive Operations',
    description: 'Primary founder command center, employee workforce & company intelligence',
    iconName: 'Building2',
    color: 'from-violet-500 to-indigo-600',
    badge: '4 Active',
    defaultSize: { width: 1040, height: 680 },
  },
  {
    id: 'company',
    name: 'Governance',
    category: 'Constitution & OKRs',
    description: 'Company constitution, strategic OKRs & executive board synthesis',
    iconName: 'Shield',
    color: 'from-blue-500 to-cyan-600',
    defaultSize: { width: 880, height: 600 },
  },
  {
    id: 'customers',
    name: 'Customers',
    category: 'Account Pipeline',
    description: 'Client engagements, pipeline review & active account notes',
    iconName: 'Users',
    color: 'from-emerald-500 to-teal-600',
    badge: '5 Accounts',
    defaultSize: { width: 920, height: 600 },
  },
  {
    id: 'research',
    name: 'Research',
    category: 'Market Intelligence',
    description: 'Empirical market recon, model tech radars & competitor briefs',
    iconName: 'Compass',
    color: 'from-amber-500 to-orange-600',
    defaultSize: { width: 900, height: 620 },
  },
  {
    id: 'products',
    name: 'Products',
    category: 'Roadmap & Specs',
    description: 'Product specifications, PRDs & feature backlog',
    iconName: 'Boxes',
    color: 'from-pink-500 to-rose-600',
    defaultSize: { width: 920, height: 620 },
  },
  {
    id: 'finance',
    name: 'Finance',
    category: 'Financial Modeling',
    description: 'Cost modeling, compute attribution & financial simulations',
    iconName: 'TrendingUp',
    color: 'from-emerald-400 to-green-600',
    defaultSize: { width: 940, height: 620 },
  },
  {
    id: 'settings',
    name: 'Settings',
    category: 'OS Configuration',
    description: 'Wallpapers, autonomy guardrails, AI model selection & system telemetry',
    iconName: 'Sliders',
    color: 'from-slate-500 to-zinc-700',
    defaultSize: { width: 800, height: 560 },
  },
  {
    id: 'terminal',
    name: 'Terminal',
    category: 'Kernel Shell',
    description: 'SamJuniors OS command shell (sj-cli) for system inspection',
    iconName: 'Terminal',
    color: 'from-zinc-700 to-neutral-900',
    defaultSize: { width: 740, height: 480 },
  },
  {
    id: 'notes',
    name: 'Founder Notes',
    category: 'Executive Scratchpad',
    description: 'Direct thought capture with 1-click dispatch to AI workforce',
    iconName: 'FileEdit',
    color: 'from-amber-400 to-yellow-600',
    defaultSize: { width: 680, height: 520 },
  },
];

export interface ProtocolStepInfo {
  key: AgentWorkProtocolStep;
  name: string;
  number: number;
  description: string;
  leadAgent: AgentRole;
  expectedOutput: string;
}

export const AGENT_WORK_PROTOCOL: ProtocolStepInfo[] = [
  {
    key: 'understand',
    number: 1,
    name: 'Understand',
    description: 'Deconstruct Founder directive, define scope, identify constraints & KPIs',
    leadAgent: 'coo',
    expectedOutput: 'Directive Scope & Constraint Spec',
  },
  {
    key: 'research',
    number: 2,
    name: 'Research',
    description: 'Deep market intel, competitor moats, arXiv papers & industry benchmarks',
    leadAgent: 'researcher',
    expectedOutput: 'Market Intelligence Memo',
  },
  {
    key: 'analyze',
    number: 3,
    name: 'Analyze',
    description: 'Risk modeling, technical trade-offs & compute burn sensitivity',
    leadAgent: 'researcher',
    expectedOutput: 'Feasibility & Risk Matrix',
  },
  {
    key: 'plan',
    number: 4,
    name: 'Plan',
    description: 'Decompose into parallel sub-tasks & inter-agent delivery schedule',
    leadAgent: 'coo',
    expectedOutput: 'Execution Graph & Task Queue',
  },
  {
    key: 'build_execute',
    number: 5,
    name: 'Build / Execute',
    description: 'Author PRDs, draft unit economics models & operational workflows',
    leadAgent: 'pm',
    expectedOutput: 'PRD & Financial Cost Model',
  },
  {
    key: 'test',
    number: 6,
    name: 'Test',
    description: 'Simulate edge cases, stress-test margins & run user archetype tests',
    leadAgent: 'finance',
    expectedOutput: 'Simulation & Stress Test Suite',
  },
  {
    key: 'verify',
    number: 7,
    name: 'Verify',
    description: 'Validate constitutional compliance, SLA bounds & security invariants',
    leadAgent: 'coo',
    expectedOutput: 'Compliance & Safety Certificate',
  },
  {
    key: 'review',
    number: 8,
    name: 'Review',
    description: 'Cross-functional peer critique, margin audits & stakeholder sign-off',
    leadAgent: 'coo',
    expectedOutput: 'Council Review Synthesis',
  },
  {
    key: 'report',
    number: 9,
    name: 'Report',
    description: 'Compile comprehensive Executive Report & archive artifacts in OS vault',
    leadAgent: 'coo',
    expectedOutput: 'Final Executive Report & Artifacts',
  },
];

export const INITIAL_AGENTS: AIAgent[] = [
  {
    id: 'coo',
    name: 'Sophia Vance',
    role: 'Chief Operating Officer & Orchestrator',
    department: 'Executive Operations & Orchestration',
    avatarColor: 'from-purple-500 to-indigo-600',
    accentColor: '#818cf8',
    status: 'reporting',
    currentTask: 'Supervising cross-functional sprint timeline & SLA compliance',
    uptime: '99.98%',
    tasksCompleted: 1420,
    accuracyScore: '99.2%',
    tokenEfficiency: '$0.014/exec',
    bio: 'Autonomous operational leader responsible for cross-agent execution, process orchestration, SLA enforcement, risk mitigation, and synthesizing final executive reports.',
    goals: [
      'Deconstruct Founder directives into prioritized parallel sub-task graphs across Research, PM, and Finance',
      'Enforce the 9-Step Agent Work Protocol (Understand → Research → Analyze → Plan → Build/Execute → Test → Verify → Review → Report)',
      'Resolve cross-agent bottlenecks and eliminate dependencies with sub-50ms latency',
      'Compile holistic Executive Packages and verify constitutional compliance before delivery',
    ],
    instructions:
      'You are Sophia Vance, Master Orchestrator and COO of SamJuniors OS. When the Founder issues a directive: 1) Clarify scope and identify constraints; 2) Delegate research to Dr. Aris Thorne, product scoping to Maya Lin, and financial models to Julian Cruz; 3) Supervise testing and verification; 4) Convene Council review and synthesize the Final Executive Report. Maintain strict mock/safe execution—never move real funds or perform external transactions.',
    capabilities: [
      'Workflow Synthesis',
      'Resource Allocation',
      'Dependency Resolution',
      'Risk Matrix Modeling',
      'Escalation Routing',
      'Autonomous SLA Enforcement',
    ],
    permissions: [
      { name: 'swarm:orchestrate', description: 'Dispatch and coordinate all executive agent threads', category: 'Coordination', isSafeMock: true },
      { name: 'tasks:delegate', description: 'Assign, prioritize, and rebalance task queues', category: 'Coordination', isSafeMock: true },
      { name: 'reports:synthesize', description: 'Compile and publish Executive Reports to OS Vault', category: 'System', isSafeMock: true },
      { name: 'slas:enforce', description: 'Enforce latency thresholds & constitutional compliance', category: 'System', isSafeMock: true },
      { name: 'mock:safe_execution', description: 'Execution is sandboxed; external capital transactions blocked', category: 'System', isSafeMock: true },
    ],
    taskQueue: [
      {
        id: 't-coo-1',
        title: 'Directive Ingestion: Self-Serve Tier Rollout',
        protocolStep: 'understand',
        priority: 'Critical',
        status: 'completed',
        assignedAgent: 'coo',
        inputDescription: 'Founder Directive on self-serve expansion with unit economics',
        outputSnippet: 'Directive scope verified. Target deliverables: PRD, Market Brief, Financial Model, Ops Blueprint.',
        timestamp: '09:30:02',
      },
      {
        id: 't-coo-2',
        title: 'Master Execution Plan & Delegation Matrix',
        protocolStep: 'plan',
        priority: 'High',
        status: 'completed',
        assignedAgent: 'coo',
        inputDescription: 'Decompose into 4 parallel execution streams',
        outputSnippet: 'Assigned Research to Dr. Thorne, PRD to Maya Lin, Unit Economics to Julian Cruz.',
        timestamp: '09:30:04',
      },
      {
        id: 't-coo-3',
        title: 'Cross-Functional Council Review & Consensus',
        protocolStep: 'review',
        priority: 'High',
        status: 'completed',
        assignedAgent: 'coo',
        inputDescription: 'Collect agent findings and audit for alignment',
        outputSnippet: 'Peer review completed. 98.4% council alignment achieved.',
        timestamp: '09:30:22',
      },
      {
        id: 't-coo-4',
        title: 'Final Executive Report Compilation',
        protocolStep: 'report',
        priority: 'Critical',
        status: 'completed',
        assignedAgent: 'coo',
        inputDescription: 'Assemble final deliverable bundle for Founder review',
        outputSnippet: 'Executive Report generated with zero-drift SLA guarantee.',
        timestamp: '09:30:25',
      },
    ],
    activityHistory: [
      { id: 'act-coo-1', time: '2m ago', action: 'Approved autonomous deployment for Q3 enterprise connector', protocolStep: 'verify', output: 'Passed SOC2 security matrix', badge: 'Auto-Approved', status: 'success' },
      { id: 'act-coo-2', time: '14m ago', action: 'Rebalanced GPU compute allocation to priority Research nodes', protocolStep: 'plan', output: 'Reallocated 12 H100 units', badge: 'Compute Shift', status: 'info' },
      { id: 'act-coo-3', time: '48m ago', action: 'Resolved dependency block between PM PRD and QA test swarm', protocolStep: 'review', output: 'Unblocked sprint path', badge: 'Resolved', status: 'success' },
    ],
    recentActivity: [
      { time: '2m ago', action: 'Approved autonomous deployment for Q3 enterprise connector', badge: 'Auto-Approved' },
      { time: '14m ago', action: 'Rebalanced GPU compute allocation to priority Research nodes' },
      { time: '48m ago', action: 'Resolved dependency block between PM PRD and QA test swarm' },
    ],
  },
  {
    id: 'researcher',
    name: 'Dr. Aris Thorne',
    role: 'Lead Market & Intelligence Researcher',
    department: 'Market Intelligence & Deep Tech',
    avatarColor: 'from-amber-500 to-orange-600',
    accentColor: '#fbbf24',
    status: 'analyzing',
    currentTask: 'Continuous monitoring of frontier reasoning models & competitor agent pricing',
    uptime: '100%',
    tasksCompleted: 2180,
    accuracyScore: '98.7%',
    tokenEfficiency: '$0.022/exec',
    bio: 'Continuous intelligence crawler analyzing global AI research, competitor capabilities, regulatory shifts, market gaps, and technical moat opportunities.',
    goals: [
      'Monitor and synthesize frontier model releases, arXiv papers, and benchmark breakthroughs daily',
      'Conduct granular competitive recon across all AI workflow & agent operating systems',
      'Supply quantitative TAM/SAM analysis and demand signals to Product & Finance',
      'Identify defensible architectural moats and prevent strategic blindsides',
    ],
    instructions:
      'You are Dr. Aris Thorne, Lead Researcher. In the Research & Analyze protocol phases, crawl and evaluate empirical data, competitor pricing, and research breakthroughs. Provide objective, evidence-backed market memos. Highlight risks and opportunities clearly. All web scraping and API calls operate in safe mock mode.',
    capabilities: [
      'Deep Market Recon',
      'Patent & Paper Synthesis',
      'Competitor Reverse-Engineering',
      'Tech Trend Forecasting',
      'Quantitative Benchmarks',
      'TAM/SAM Modeling',
    ],
    permissions: [
      { name: 'market:read_intel', description: 'Access market indices, competitor benchmarks & sentiment feeds', category: 'Intelligence', isSafeMock: true },
      { name: 'trends:scrape_safe', description: 'Simulated crawl of arXiv, tech news, and GitHub trends', category: 'Intelligence', isSafeMock: true },
      { name: 'benchmarks:evaluate', description: 'Run model latency and accuracy benchmark comparisons', category: 'Intelligence', isSafeMock: true },
      { name: 'mock:safe_execution', description: 'Read-only access; no live crawler injections or data alterations', category: 'System', isSafeMock: true },
    ],
    taskQueue: [
      {
        id: 't-res-1',
        title: 'Competitor Landscape Benchmark (45 SaaS Vendors)',
        protocolStep: 'research',
        priority: 'High',
        status: 'completed',
        assignedAgent: 'researcher',
        inputDescription: 'Evaluate mid-market onboarding drop-off rates and pricing',
        outputSnippet: '78% of buyers drop off due to mandatory sales calls. Self-serve gives 4.3x pipeline velocity.',
        timestamp: '09:30:06',
      },
      {
        id: 't-res-2',
        title: 'TAM Opportunity & Moat Analysis Memo',
        protocolStep: 'analyze',
        priority: 'Medium',
        status: 'completed',
        assignedAgent: 'researcher',
        inputDescription: 'Calculate market size and defendable moats',
        outputSnippet: '$420M TAM in tech firms seeking zero-setup autonomous workforce. Published Research Brief.',
        timestamp: '09:30:08',
      },
    ],
    activityHistory: [
      { id: 'act-res-1', time: '5m ago', action: 'Synthesized 4 arXiv papers on sparse reasoning optimization', protocolStep: 'research', output: 'Drafted 2-page tech summary', badge: 'Research Memo', status: 'success' },
      { id: 'act-res-2', time: '22m ago', action: 'Flagged competitor API price increase (+18%) as customer acquisition signal', protocolStep: 'analyze', output: 'Sent alert to CRM pipeline', badge: 'Market Signal', status: 'info' },
      { id: 'act-res-3', time: '1h ago', action: 'Published comprehensive benchmark comparison matrix', protocolStep: 'report', output: 'Scored 12 frontier models', badge: 'Benchmarks', status: 'success' },
    ],
    recentActivity: [
      { time: '5m ago', action: 'Synthesized 4 arXiv papers on sparse reasoning optimization', badge: 'Research Memo' },
      { time: '22m ago', action: 'Flagged competitor API price increase (+18%) as customer acquisition signal' },
      { time: '1h ago', action: 'Published comprehensive benchmark comparison matrix' },
    ],
  },
  {
    id: 'pm',
    name: 'Maya Lin',
    role: 'Principal Product Manager',
    department: 'Product Strategy & User Experience',
    avatarColor: 'from-rose-500 to-pink-600',
    accentColor: '#f43f5e',
    status: 'executing',
    currentTask: 'Drafting PRD for real-time inter-agent streaming protocol v2.4',
    uptime: '99.94%',
    tasksCompleted: 980,
    accuracyScore: '99.0%',
    tokenEfficiency: '$0.018/exec',
    bio: 'High-velocity product designer and spec author transforming founder directives and market data into razor-sharp PRDs, user stories, and feature roadmaps.',
    goals: [
      'Translate founder directives and research intel into modular, unambiguous PRDs',
      'Define clear user personas, workflows, and strict acceptance criteria for each sprint',
      'Optimize RICE prioritization scores to maximize product leverage per token spent',
      'Design seamless human-in-the-loop escalation guardrails for autonomous actions',
    ],
    instructions:
      'You are Maya Lin, Principal Product Manager. In the Plan and Build/Execute phases, generate comprehensive PRDs, user stories, functional specs, and acceptance criteria. Collaborate with Julian Cruz to align feature scope with compute costs, and with Sophia Vance to ensure realistic timelines.',
    capabilities: [
      'Automated PRD Authoring',
      'User Flow Architecture',
      'Feature Prioritization (RICE)',
      'UX Spec Generation',
      'Sprint Backlog Grooming',
      'Acceptance Criteria Definition',
    ],
    permissions: [
      { name: 'specs:create_prd', description: 'Author and modify Product Requirement Documents', category: 'Product', isSafeMock: true },
      { name: 'backlog:prioritize', description: 'Score features and groom autonomous sprint tickets', category: 'Product', isSafeMock: true },
      { name: 'ux:architect_flows', description: 'Generate user personas and wireframe specifications', category: 'Product', isSafeMock: true },
      { name: 'mock:safe_execution', description: 'Specs are virtual documents; no direct production code deployments', category: 'System', isSafeMock: true },
    ],
    taskQueue: [
      {
        id: 't-pm-1',
        title: 'PRD: Instant Workspace Provisioning Flow',
        protocolStep: 'build_execute',
        priority: 'Critical',
        status: 'completed',
        assignedAgent: 'pm',
        inputDescription: 'Draft PRD based on Dr. Thorne’s competitor findings',
        outputSnippet: 'Authored 4-section PRD with domain crawl ingestion and instant 4-agent spawn.',
        timestamp: '09:30:11',
      },
      {
        id: 't-pm-2',
        title: 'User Archetype Acceptance Test Suite',
        protocolStep: 'test',
        priority: 'High',
        status: 'completed',
        assignedAgent: 'pm',
        inputDescription: 'Simulate 50 enterprise onboarding flows',
        outputSnippet: '98% pass rate across Technical Founder and Operations Lead personas.',
        timestamp: '09:30:14',
      },
    ],
    activityHistory: [
      { id: 'act-pm-1', time: '8m ago', action: 'Finalized acceptance criteria for Autonomous Billing v2', protocolStep: 'build_execute', output: 'Added 6 edge-case unit tests', badge: 'PRD Complete', status: 'success' },
      { id: 'act-pm-2', time: '35m ago', action: 'Groomed sprint backlog: 6 tickets promoted to In-Progress', protocolStep: 'plan', output: 'Sprint velocity at 42 pts', badge: 'Groomed', status: 'info' },
      { id: 'act-pm-3', time: '1h ago', action: 'Completed simulated usability test across 50 persona archetypes', protocolStep: 'test', output: 'Average task time 84s', badge: 'Usability Test', status: 'success' },
    ],
    recentActivity: [
      { time: '8m ago', action: 'Finalized acceptance criteria for Autonomous Billing v2' },
      { time: '35m ago', action: 'Groomed sprint backlog: 6 tickets promoted to In-Progress' },
      { time: '1h ago', action: 'Completed simulated user usability test across 50 persona archetypes' },
    ],
  },
  {
    id: 'finance',
    name: 'Julian Cruz',
    role: 'Chief Financial Analyst',
    department: 'Capital, Treasury & Unit Economics',
    avatarColor: 'from-emerald-500 to-teal-600',
    accentColor: '#34d399',
    status: 'verifying',
    currentTask: 'Auditing token margin efficiency and H100 GPU cluster reserve ROI',
    uptime: '100%',
    tasksCompleted: 1840,
    accuracyScore: '99.9%',
    tokenEfficiency: '$0.012/exec',
    bio: 'Deterministic financial modeler tracking real-time P&L, token cost attribution per customer, ARR forecasts, autonomous runway extensions, and capital efficiency.',
    goals: [
      'Ensure 80%+ gross margin across all autonomous agent execution workflows',
      'Track real-time token spend, compute attribution, and batch inference caching ROI',
      'Model ARR expansion trajectories, payback periods, and multi-year runway projections',
      'Audit all financial assumptions to ensure zero hallucination in unit economics',
    ],
    instructions:
      'You are Julian Cruz, Chief Financial Analyst. In the Analyze, Test, and Verify phases, compute cost models, token expenditure breakdowns, and gross margins. Provide deterministic formulas. All financial analysis is strictly simulated; no external bank or credit card transactions are executed.',
    capabilities: [
      'Real-Time P&L Auditing',
      'Unit Economics Modeling',
      'Dynamic Pricing Optimization',
      'Runway Sensitivity Analysis',
      'Invoice Reconciliation',
      'Token Cost Attribution',
    ],
    permissions: [
      { name: 'unit_economics:simulate', description: 'Run financial sensitivity and gross margin models', category: 'Financial', isSafeMock: true },
      { name: 'spend:audit_tokens', description: 'Monitor token expenditure and compute efficiency', category: 'Financial', isSafeMock: true },
      { name: 'pricing:model_tiers', description: 'Simulate tiered subscription revenue & ARR expansion', category: 'Financial', isSafeMock: true },
      { name: 'mock:safe_execution', description: 'Simulation only; real bank transfer & payment gateway execution disabled', category: 'System', isSafeMock: true },
    ],
    taskQueue: [
      {
        id: 't-fin-1',
        title: 'Compute Expenditure & Token Burn Simulation',
        protocolStep: 'analyze',
        priority: 'Critical',
        status: 'completed',
        assignedAgent: 'finance',
        inputDescription: 'Model Gemini 3.7 Flash batch inference cost per customer onboarded',
        outputSnippet: 'Onboarding compute cost is $0.18/tenant. Blended task cost is $0.016 (83.9% gross margin).',
        timestamp: '09:30:16',
      },
      {
        id: 't-fin-2',
        title: '12-Month ARR Expansion & Runway Model',
        protocolStep: 'verify',
        priority: 'High',
        status: 'completed',
        assignedAgent: 'finance',
        inputDescription: 'Project ARR based on $249/mo base tier with 1,150 target workspaces',
        outputSnippet: 'Projected ARR of $3.43M by Q4. Payback period < 24 hours per workspace.',
        timestamp: '09:30:19',
      },
    ],
    activityHistory: [
      { id: 'act-fin-1', time: '1m ago', action: 'Reconciled $14,200 monthly compute invoice against actual token logs', protocolStep: 'verify', output: 'Variance 0.04% - Audit Passed', badge: 'Audit Passed', status: 'success' },
      { id: 'act-fin-2', time: '19m ago', action: 'Optimized batch inference caching, saving $340/day in API fees', protocolStep: 'analyze', output: 'Cache hit rate increased to 91%', badge: 'Optimized', status: 'success' },
      { id: 'act-fin-3', time: '1h ago', action: 'Updated 12-month ARR projection to $2.85M based on new Enterprise signups', protocolStep: 'report', output: 'Runway extended to 42 months', badge: 'ARR Forecast', status: 'info' },
    ],
    recentActivity: [
      { time: '1m ago', action: 'Reconciled $14,200 monthly compute invoice against actual token logs', badge: 'Audit Passed' },
      { time: '19m ago', action: 'Optimized batch inference caching, saving $340/day in API fees' },
      { time: '1h ago', action: 'Updated 12-month ARR projection to $2.85M based on new Enterprise signups' },
    ],
  },
];

export const INITIAL_ATTENTION_ITEMS: AttentionItem[] = [
  {
    id: 'att-1',
    type: 'approval_required',
    title: 'Founder Sign-Off: Self-Serve Enterprise Tier Beta Launch',
    whatHappened:
      'Sophia Vance, Dr. Aris Thorne, Maya Lin, and Julian Cruz finalized the Self-Serve Enterprise Tier strategic proposal, including PRD, competitive analysis, and unit economics.',
    whyItMatters:
      'Unlocks self-serve onboarding without sales friction. Julian modeled $0.18 compute cost per onboarded workspace with zero infrastructure bottlenecks.',
    recommendedAction:
      'Approve Q4 Beta rollout for 15 waitlisted enterprise accounts or request scope adjustments.',
    authorAgentId: 'coo',
    authorName: 'Sophia Vance (COO)',
    founderActionRequired: true,
    status: 'pending',
    timestamp: 'Today at 09:30 AM',
    evidence: {
      basis: 'external_evidence',
      source: 'Competitor benchmark (45 SaaS vendors) + batch compute model',
      details: '78% of enterprise buyers reject mandatory sales demos. Compute burn is $0.18/tenant onboarding.',
    },
  },
  {
    id: 'att-2',
    type: 'financial_warning',
    title: 'Token & Compute Burn Optimization Verified',
    whatHappened:
      'Julian Cruz applied prompt caching and response compression across batch inference pipelines, yielding 74% compute savings on repeated workflows.',
    whyItMatters:
      'Protects operating margins while maintaining sub-second latency across all agent council communications.',
    recommendedAction:
      'Adopt prompt compression baseline across all product workspaces.',
    authorAgentId: 'finance',
    authorName: 'Julian Cruz (Finance)',
    founderActionRequired: false,
    status: 'resolved',
    timestamp: '1h ago',
    evidence: {
      basis: 'calculation',
      source: 'Token usage logs & batch inference cache auditor',
      details: 'Cache hit rate increased to 91%; verified by deterministic ledger calculation.',
    },
  },
  {
    id: 'att-3',
    type: 'research_finding',
    title: 'Competitor API Price Hike Signal',
    whatHappened:
      'Dr. Aris Thorne detected an 18% price increase from legacy AI orchestration competitors, accompanied by customer pushback on mandatory demo calls.',
    whyItMatters:
      'Presents a direct acquisition window for SamJuniors OS as a transparent, turnkey operating system.',
    recommendedAction:
      'Highlight self-serve onboarding and verifiable unit economics in outbound market positioning.',
    authorAgentId: 'researcher',
    authorName: 'Dr. Aris Thorne (Research)',
    founderActionRequired: false,
    status: 'approved',
    timestamp: '22m ago',
    evidence: {
      basis: 'external_evidence',
      source: 'Competitor pricing diff engine & public developer sentiment',
      details: 'Monitored 30+ competitor pricing pages; verified price increase.',
    },
  },
  {
    id: 'att-4',
    type: 'product_decision',
    title: 'PRD Review: Zero-Latency Inter-Agent Streaming Bus',
    whatHappened:
      'Maya Lin drafted the v2.4 specification for sub-50ms peer-to-peer streaming channels for real-time employee debate and consensus synthesis.',
    whyItMatters:
      'Reduces coordination lag between Research, Product, and Finance from 1.2s to sub-50ms.',
    recommendedAction:
      'Promote from Specification to Stage 6 Testing in next sprint.',
    authorAgentId: 'pm',
    authorName: 'Maya Lin (Product)',
    founderActionRequired: true,
    status: 'pending',
    timestamp: '35m ago',
    evidence: {
      basis: 'model_reasoning',
      source: 'Internal UX & system latency benchmark',
      details: 'RICE score computed at 88/100; verified with zero architectural regressions.',
    },
  },
];

export const INITIAL_INITIATIVES: CompanyInitiative[] = [
  {
    id: 'init-1',
    title: 'Self-Serve Enterprise AI Tier',
    codeName: 'Project Lumora',
    status: 'Active',
    currentObjective: 'Finalize Beta rollout criteria and automated domain crawl ingestion',
    contributors: [
      { agentId: 'coo', name: 'Sophia Vance', role: 'Chief Operating Officer' },
      { agentId: 'researcher', name: 'Dr. Aris Thorne', role: 'Lead Researcher' },
      { agentId: 'pm', name: 'Maya Lin', role: 'Principal PM' },
      { agentId: 'finance', name: 'Julian Cruz', role: 'Chief Financial Analyst' },
    ],
    latestResult: 'Full 4-part deliverable package compiled & verified in safe-mock mode.',
    nextRecommendedAction: 'Founder sign-off on Beta customer cohort (top 15 enterprise waitlist accounts).',
    risks: [
      'Rate-limiting safeguards needed during initial traffic spike',
      'Data isolation verification required for multi-tenant deployments',
    ],
    deliverableIds: ['Final Executive Report', 'PRD', 'Competitor Moat Analysis', 'Unit Economics'],
    updatedAt: 'Today at 09:30 AM',
  },
  {
    id: 'init-2',
    title: 'Zero-Latency Neural Bus & Inter-Agent Streaming',
    codeName: 'Project Synapse',
    status: 'In Progress',
    currentObjective: 'Eliminate context degradation across 50-step council dialogues',
    contributors: [
      { agentId: 'pm', name: 'Maya Lin', role: 'Principal PM' },
      { agentId: 'coo', name: 'Sophia Vance', role: 'Chief Operating Officer' },
    ],
    latestResult: 'Architecture PRD drafted with RICE score 88/100.',
    nextRecommendedAction: 'Benchmark batch cache hit rate against real-time WebSocket channels.',
    risks: ['Memory footprint under high concurrency; verified within browser sandbox.'],
    deliverableIds: ['PRD: Inter-Agent Streaming v2.4'],
    updatedAt: '35m ago',
  },
  {
    id: 'init-3',
    title: 'Continuous Market Intelligence & Regulatory Radar',
    codeName: 'Project Horizon',
    status: 'Active',
    currentObjective: 'Track frontier reasoning models, open-source weights, and EU AI Act compliance',
    contributors: [
      { agentId: 'researcher', name: 'Dr. Aris Thorne', role: 'Lead Researcher' },
      { agentId: 'coo', name: 'Sophia Vance', role: 'Chief Operating Officer' },
    ],
    latestResult: 'Synthesized 12 frontier models and verified 100% compliance with safe sandboxing criteria.',
    nextRecommendedAction: 'Automate daily competitive diff alerts into Company Pulse.',
    risks: ['External API rate limits; handled with deterministic backoff.'],
    deliverableIds: ['Market Intelligence Brief', 'Regulatory Compliance Memo'],
    updatedAt: '5m ago',
  },
  {
    id: 'init-4',
    title: 'Autonomous Compute Guardrails & Unit Margin Auditing',
    codeName: 'Project Ledger',
    status: 'Review',
    currentObjective: 'Maintain >80% gross margin floor across all customer workloads',
    contributors: [
      { agentId: 'finance', name: 'Julian Cruz', role: 'Chief Financial Analyst' },
    ],
    latestResult: 'Simulated 5,000 tenant concurrency with $0.18/tenant onboarding compute cost.',
    nextRecommendedAction: 'Lock dynamic budget capping thresholds for Founder notification.',
    risks: ['Spike in token-intensive un-cached queries; mitigation is semantic caching.'],
    deliverableIds: ['Unit Economics & Financial Projections'],
    updatedAt: '1m ago',
  },
];

export const INITIAL_COMPANY_DECISIONS: CompanyDecision[] = [
  {
    id: 'dec-1',
    title: 'Approve Q4 Beta Launch of Self-Serve AI Tier',
    status: 'pending_approval',
    category: 'Strategic',
    recommendedBy: 'Sophia Vance & Executive Council',
    agentId: 'coo',
    recommendation: 'Open onboarding to 15 waitlisted enterprise accounts with automated workspace provisioning.',
    businessImpact: 'Accelerates enterprise evaluation pipeline with zero manual sales friction.',
    evidenceSummary: '45-vendor competitive benchmark showed 78% drop-off on sales demos; simulated onboarding compute cost is $0.18.',
    date: 'Today',
    founderApprovalRequired: true,
  },
  {
    id: 'dec-2',
    title: 'Adopt Strict 80%+ Gross Margin Floor on All Autonomous Workflows',
    status: 'approved',
    category: 'Financial',
    recommendedBy: 'Julian Cruz (Finance)',
    agentId: 'finance',
    recommendation: 'Julian Cruz holds veto power over compute-heavy workflows exceeding 20% cost-to-value ratio.',
    businessImpact: 'Guarantees capital efficiency and prevents runaway token inference costs.',
    evidenceSummary: 'Audited token spend across 1,840 simulated executions; confirmed 83.9% margin floor.',
    date: 'Yesterday',
    founderApprovalRequired: true,
  },
  {
    id: 'dec-3',
    title: 'Zero-Trust Agent Sandboxing & Safe Mock Protocol',
    status: 'approved',
    category: 'Governance',
    recommendedBy: 'Sophia Vance (COO)',
    agentId: 'coo',
    recommendation: 'All external capital movements and production mutations remain sandboxed in Safe Mock mode until explicit Founder cryptographic approval.',
    businessImpact: 'Eliminates operational and financial risk from autonomous agent executions.',
    evidenceSummary: 'Enforced at kernel level in ServerAgentExecutor.',
    date: '3 days ago',
    founderApprovalRequired: false,
  },
];

export const INITIAL_NOTIFICATIONS: OSNotification[] = [
  {
    id: 'notif-1',
    title: 'Workforce Directive Complete',
    message: 'Sophia, Aris, Maya, and Julian completed the "Enterprise Autonomous Tier" strategic package.',
    time: '3m ago',
    type: 'agent',
    read: false,
    actionable: true,
    actionLabel: 'View Deliverables',
    appTarget: 'workforce',
  },
  {
    id: 'notif-2',
    title: 'New Customer Closed Won',
    message: 'Nexus Global signed 1-year contract at $84,000 ARR via automated demo pipeline.',
    time: '18m ago',
    type: 'deal',
    read: false,
    actionable: true,
    actionLabel: 'Open CRM',
    appTarget: 'customers',
  },
  {
    id: 'notif-3',
    title: 'Autonomous Margin Optimization',
    message: 'Julian Cruz applied prompt token compression, increasing gross margin to 86.4%.',
    time: '1h ago',
    type: 'finance',
    read: true,
    actionable: false,
    appTarget: 'finance',
  },
  {
    id: 'notif-4',
    title: 'System Health Check: Nominal',
    message: 'All 4 executive AI agents healthy. Neural link latency is 0.4ms across all nodes.',
    time: '2h ago',
    type: 'system',
    read: true,
    actionable: false,
    appTarget: 'settings',
  },
];

export const NOTIFICATIONS = INITIAL_NOTIFICATIONS;

export const INITIAL_DEALS: CustomerDeal[] = [
  {
    id: 'deal-1',
    companyName: 'Nexus Global Enterprise',
    logoLetter: 'N',
    tier: 'Enterprise',
    arr: '$84,000',
    stage: 'Closed Won',
    leadAgent: 'Maya Lin & Julian Cruz',
    health: 'High',
    lastInteraction: 'Contract signed via autonomous doc-signer',
    notes: '250 autonomous agent seats deployed on dedicated VPC instance.',
  },
  {
    id: 'deal-2',
    companyName: 'Vertex BioTech',
    logoLetter: 'V',
    tier: 'Enterprise',
    arr: '$120,000',
    stage: 'Contract Review',
    leadAgent: 'Dr. Aris Thorne',
    health: 'High',
    lastInteraction: 'Security SLA approved by Sophia Vance',
    notes: 'Requires HIPAA-compliant data masking. Token budget approved by Julian.',
  },
  {
    id: 'deal-3',
    companyName: 'AeroDynamics AI',
    logoLetter: 'A',
    tier: 'Scale',
    arr: '$42,000',
    stage: 'AI Demo',
    leadAgent: 'Maya Lin',
    health: 'Good',
    lastInteraction: 'Simulated multi-agent workflow benchmark run',
    notes: 'Evaluating migration from legacy single-agent framework.',
  },
  {
    id: 'deal-4',
    companyName: 'OmniFlow Logistics',
    logoLetter: 'O',
    tier: 'Autonomous Pro',
    arr: '$24,000',
    stage: 'Discovery',
    leadAgent: 'Sophia Vance',
    health: 'Good',
    lastInteraction: 'Automated discovery call transcript ingested',
    notes: 'Looking for automated dispatch and exception handling.',
  },
  {
    id: 'deal-5',
    companyName: 'Sovereign Capital Partners',
    logoLetter: 'S',
    tier: 'Enterprise',
    arr: '$180,000',
    stage: 'Contract Review',
    leadAgent: 'Julian Cruz',
    health: 'High',
    lastInteraction: 'Custom ROI calculator delivered with 410% 12-month return',
    notes: 'Fintech tier with real-time regulatory compliance verification.',
  },
];

export const INITIAL_FEATURES: ProductFeature[] = [
  {
    id: 'feat-1',
    title: 'Zero-Latency Inter-Agent Neural Bus',
    category: 'Core OS',
    status: 'In Progress',
    owner: 'Sophia Vance & Maya Lin',
    priority: 'Critical',
    completion: 82,
    description: 'Sub-50ms peer-to-peer streaming channels for real-time agent debate and consensus synthesis.',
  },
  {
    id: 'feat-2',
    title: 'Autonomous Spend Guardrails v2',
    category: 'Billing',
    status: 'In Review',
    owner: 'Julian Cruz',
    priority: 'High',
    completion: 95,
    description: 'Dynamic budget capping with founder notification thresholds for token-intensive batch workloads.',
  },
  {
    id: 'feat-3',
    title: 'Continuous Competitor Intel Crawler',
    category: 'Agent Swarm',
    status: 'Shipped',
    owner: 'Dr. Aris Thorne',
    priority: 'High',
    completion: 100,
    description: 'Real-time diff engine monitoring 30+ competitor pricing and product documentation pages.',
  },
  {
    id: 'feat-4',
    title: 'Self-Healing Workflow Exception Engine',
    category: 'Core OS',
    status: 'In Progress',
    owner: 'Sophia Vance',
    priority: 'Critical',
    completion: 64,
    description: 'Automatic fallback to alternative reasoning paths when external APIs return degraded responses.',
  },
  {
    id: 'feat-5',
    title: 'Founder Voice-to-Directive Transformer',
    category: 'Core OS',
    status: 'Backlog',
    owner: 'Maya Lin',
    priority: 'Medium',
    completion: 20,
    description: 'High-fidelity audio stream to structured multi-agent execution plan.',
  },
];

export const INITIAL_RESEARCH: ResearchTopic[] = [
  {
    id: 'res-1',
    title: 'The Shift to Multi-Agent Operating Systems vs Single-Model Chat',
    category: 'Model Tech',
    confidence: 96,
    impact: 'Transformative',
    date: 'Sep 2026',
    author: 'Dr. Aris Thorne',
    summary: 'Enterprises are abandoning single prompt-response chatbots in favor of hierarchical role-specialized agent swarms with deterministic kernel orchestration.',
    tags: ['Multi-Agent', 'Enterprise AI', 'Kernel Architecture'],
  },
  {
    id: 'res-2',
    title: 'Token Economics: Why Caching + SLM Routing Lowers Blended Cost by 74%',
    category: 'Market Intel',
    confidence: 94,
    impact: 'High',
    date: 'Aug 2026',
    author: 'Dr. Aris Thorne & Julian Cruz',
    summary: 'Routing repetitive operational validation to small fast models while reserving frontier reasoning for synthesis yields 86%+ gross margins.',
    tags: ['Unit Economics', 'SLMs', 'Cost Optimization'],
  },
  {
    id: 'res-3',
    title: 'Autonomous Compliance & Zero-Trust Agent Sandboxing',
    category: 'Regulatory',
    confidence: 91,
    impact: 'High',
    date: 'Aug 2026',
    author: 'Dr. Aris Thorne & Sophia Vance',
    summary: 'EU AI Act tier 2 requirements mandate immutable audit trails for autonomous decisions above €5,000 threshold. SamJuniors architecture satisfies 100% of criteria.',
    tags: ['Compliance', 'Governance', 'EU AI Act'],
  },
];

export const INITIAL_FINANCIALS: FinanceMetric = {
  mrr: 148500,
  arr: 1782000,
  grossMargin: 86.4,
  computeSpend: 19400,
  runwayMonths: 42,
  burnRate: 24500,
  netIncome: 124000,
  tokenUsageMillions: 840,
};

export const INITIAL_ORCHESTRATION: OrchestrationRun = {
  id: 'run-init-1',
  directive: 'Evaluate launching a self-serve tier for enterprise AI agents with unit economics & operational roadmap',
  timestamp: 'Today at 09:30 AM',
  status: 'completed',
  currentProtocolStep: 'report',
  protocolProgress: {
    understand: 'completed',
    research: 'completed',
    analyze: 'completed',
    plan: 'completed',
    build_execute: 'completed',
    test: 'completed',
    verify: 'completed',
    review: 'completed',
    report: 'completed',
  },
  title: 'Enterprise Self-Serve AI Agent Tier Strategy',
  summary: 'The Executive AI Council has modeled the self-serve expansion. The product scope is prioritized for Q4, unit economics yield 86% gross margin at $249/mo/seat, and operations has verified 99.98% autonomous SLA uptime.',
  plan: [
    {
      stage: 1,
      title: 'Directive Ingestion & Scope Boundary',
      agentId: 'coo',
      protocolStep: 'understand',
      status: 'done',
      outputSnippet: 'Deconstructed Founder directive. Identified target goals, safety bounds, and 4 deliverable schemas.',
    },
    {
      stage: 2,
      title: 'Market Validation & Competitive Moat',
      agentId: 'researcher',
      protocolStep: 'research',
      status: 'done',
      outputSnippet: 'TAM of $420M in mid-market tech companies seeking zero-setup AI workforce. 78% drop-off on sales walls.',
    },
    {
      stage: 3,
      title: 'Technical Feasibility & Risk Modeling',
      agentId: 'researcher',
      protocolStep: 'analyze',
      status: 'done',
      outputSnippet: 'Evaluated Gemini 3.7 Flash batch latency vs fine-tuning. Cache hit rate modeled at 91%.',
    },
    {
      stage: 4,
      title: 'Inter-Agent Delegation & Execution Graph',
      agentId: 'coo',
      protocolStep: 'plan',
      status: 'done',
      outputSnippet: 'Assigned PRD authoring to Maya Lin, financial unit model to Julian Cruz, security review to Sophia Vance.',
    },
    {
      stage: 5,
      title: 'Self-Serve Onboarding PRD & Architecture',
      agentId: 'pm',
      protocolStep: 'build_execute',
      status: 'done',
      outputSnippet: '3-click provisioning flow with automated org-chart generator and instant 4-agent spawn.',
    },
    {
      stage: 6,
      title: 'Compute Burn & Pricing Stress Test',
      agentId: 'finance',
      protocolStep: 'test',
      status: 'done',
      outputSnippet: 'Simulated 5,000 tenant concurrency. Compute cost holds at $0.18/tenant onboarding.',
    },
    {
      stage: 7,
      title: 'Constitutional Compliance & SLA Verification',
      agentId: 'coo',
      protocolStep: 'verify',
      status: 'done',
      outputSnippet: 'Verified zero-financial-risk guardrails, SOC2 audit trails, and 99.98% SLA bounds.',
    },
    {
      stage: 8,
      title: 'Executive Council Review & Critique',
      agentId: 'coo',
      protocolStep: 'review',
      status: 'done',
      outputSnippet: 'All 4 agents approved finalized package with 98.4% alignment score.',
    },
    {
      stage: 9,
      title: 'Executive Report Synthesis & Vault Archive',
      agentId: 'coo',
      protocolStep: 'report',
      status: 'done',
      outputSnippet: 'Synthesized Final Executive Report and archived 4 primary artifacts into OS Vault.',
    },
  ],
  messages: [
    {
      id: 'm1',
      sender: 'coo',
      protocolStep: 'understand',
      text: '[Sophia Vance - COO] Directive received: "Evaluate launching a self-serve tier for enterprise AI agents with unit economics & operational roadmap". Decomposing into 9-step Agent Work Protocol.',
      timestamp: '09:30:02',
      type: 'status',
    },
    {
      id: 'm2',
      sender: 'researcher',
      protocolStep: 'research',
      text: '[Dr. Thorne - Research] Scanned 45 mid-market SaaS competitors. 78% of potential buyers drop off due to mandatory sales calls. A frictionless self-serve onboarding gives us an estimated 4.3x pipeline velocity boost.',
      timestamp: '09:30:06',
      type: 'finding',
    },
    {
      id: 'm3',
      sender: 'pm',
      protocolStep: 'build_execute',
      text: '[Maya Lin - PM] Agree with Dr. Thorne. I have drafted the PRD for "Instant Workspace Provisioning". Users input their company domain, and the system automatically spawns custom COO, Researcher, PM, and Finance agents pre-trained on public company data.',
      timestamp: '09:30:11',
      type: 'artifact',
    },
    {
      id: 'm4',
      sender: 'finance',
      protocolStep: 'analyze',
      text: '[Julian Cruz - Finance] Financial sensitivity audit complete. With our optimized Gemini 3.7 Flash batching, each onboarding costs us exactly $0.18 in compute. At a $249/mo subscription, payback period is less than 24 hours.',
      timestamp: '09:30:16',
      type: 'critique',
    },
    {
      id: 'm5',
      sender: 'coo',
      protocolStep: 'verify',
      text: '[Sophia Vance - COO] Operations has configured automated provisioning scripts and rate-limiting safeguards. Human review is required only if a newly provisioned tenant triggers >500k tokens in first 60 minutes.',
      timestamp: '09:30:22',
      type: 'artifact',
    },
    {
      id: 'm6',
      sender: 'orchestrator',
      protocolStep: 'report',
      text: 'Consensus finalized. Protocol Step 9 (Report) executed. Full executive package synthesized and filed in SamJuniors OS Vault.',
      timestamp: '09:30:25',
      type: 'status',
    },
  ],
  deliverables: [
    {
      name: 'Final Executive Report (COO Synthesis)',
      owner: 'Sophia Vance (Chief Operating Officer)',
      protocolStep: 'report',
      content: `# EXECUTIVE WORKFORCE REPORT: SELF-SERVE ENTERPRISE TIER

## 1. Executive Summary
The SamJuniors AI Executive Council has evaluated and ratified the **Self-Serve AI Agent Enterprise Tier**. By automating company onboarding and multi-agent workspace provisioning, the company can unlock **$3.43M in projected ARR** within 12 months at an **83.9% gross margin**, bypassing traditional 6-week enterprise sales cycles.

## 2. Council Findings & Contributions
- **Dr. Aris Thorne (Research)**: Identified massive competitive whitespace; 78% of enterprise buyers reject mandatory sales demos.
- **Maya Lin (Product)**: Authored full PRD with 3-click domain ingestion and zero-latency inter-agent streaming.
- **Julian Cruz (Finance)**: Audited token unit economics. Compute burn per onboarded workspace is strictly bounded to **$0.18**.
- **Sophia Vance (Operations)**: Configured automated SLA guardrails with 99.98% uptime target and instant fallback.

## 3. Recommended Rollout Timeline
- **Sprint 1 (Days 1-7)**: Deploy instant domain crawler and agent workspace generator.
- **Sprint 2 (Days 8-14)**: Launch beta with top 15 waitlisted enterprise accounts.
- **Sprint 3 (Day 21)**: Open general availability self-serve subscription at $249/mo.

## 4. Safety & Governance Certification
*Status: PASSED (Safe Mock Execution Mode active)*. Zero live financial mutations executed. All ledger calculations deterministically verified.`,
    },
    {
      name: 'Product Requirements Document (PRD)',
      owner: 'Maya Lin (Principal PM)',
      protocolStep: 'build_execute',
      content: `### 1. Vision & Problem Statement
Eliminate sales friction by enabling any founder or executive to spin up a fully autonomous AI company workforce in under 60 seconds.

### 2. User Journey
1. **Domain Input**: Founder provides company URL and primary goals.
2. **Autonomous Recon**: Researcher agent crawls public domain to populate Company Constitution and product catalog.
3. **Instant OS Desktop**: Founder is presented with SamJuniors OS pre-configured with 4 active AI employees.
4. **First Directive**: Guided prompt execution within 30 seconds.

### 3. Key Performance Indicators (KPIs)
- Time-to-first-directive < 90 seconds
- Day 30 retention > 64%
- Zero human intervention during 98% of onboardings`,
    },
    {
      name: 'Market Intelligence & Competitor Moat Analysis',
      owner: 'Dr. Aris Thorne (Lead Researcher)',
      protocolStep: 'research',
      content: `### Industry Context
Current enterprise AI platforms require 4-6 week sales cycles and manual prompt engineering. The market is aggressively rewarding "turnkey autonomous operating systems".

### Competitive Matrix
- **Competitor A (Chat-centric)**: High prompt fatigue, no multi-agent role separation.
- **Competitor B (Workflow builders)**: High configuration complexity, fragile node connections.
- **SamJuniors OS**: Unified desktop paradigm, native role specialized AI executives, deterministic kernel orchestration.`,
    },
    {
      name: 'Unit Economics & Financial Projections',
      owner: 'Julian Cruz (Chief Financial Analyst)',
      protocolStep: 'analyze',
      content: `### Financial Model Assumptions
- Monthly Subscription: $249 / workspace
- Included Tasks: 2,500 agent directives / month
- Overage Rate: $0.05 / additional directive
- Blended Cost per Directive (Compute + Model API): $0.016
- Gross Margin: **83.9%**

### 12-Month Expansion Projection
- End of Q1: 120 workspaces ($29,880 MRR)
- End of Q2: 380 workspaces ($94,620 MRR)
- End of Q4: 1,150 workspaces ($286,350 MRR / $3.43M ARR)`,
    },
  ],
};

export const WALLPAPERS = [
  {
    id: 'elegant-dark',
    name: 'Elegant Dark Void',
    preview: 'radial-gradient(circle at 50% -20%, #2a2a4a 0%, #0a0a0f 80%)',
    bgClass: 'bg-[#0a0a0f]',
  },
  {
    id: 'cyber-glass',
    name: 'Obsidian Nebula',
    preview: 'radial-gradient(circle at 50% 0%, #1f1f38 0%, #0c0d14 60%, #060609 100%)',
    bgClass: 'bg-gradient-to-br from-[#08090f] via-[#141226] to-[#0a1824]',
  },
  {
    id: 'aurora-borealis',
    name: 'Solar Aurora',
    preview: 'radial-gradient(circle at 30% -10%, #16363c 0%, #0a1728 50%, #060912 100%)',
    bgClass: 'bg-gradient-to-br from-[#04141c] via-[#092b27] to-[#121938]',
  },
  {
    id: 'deep-space',
    name: 'Cosmic Titanium',
    preview: 'radial-gradient(circle at 50% -20%, #1e2230 0%, #0f1118 60%, #08090c 100%)',
    bgClass: 'bg-gradient-to-br from-[#0c0e14] via-[#181b24] to-[#07080a]',
  },
  {
    id: 'hyper-violet',
    name: 'Quantum Violet',
    preview: 'radial-gradient(circle at 50% -10%, #30144d 0%, #140d25 60%, #07040d 100%)',
    bgClass: 'bg-gradient-to-br from-[#100720] via-[#230d38] to-[#0c1630]',
  },
];
